services:
  postgres:
    image: postgres
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
          - type: bind
            source: ./drizzle/schema.sql
            target: /docker-entrypoint-initdb.d/schema.sql
          - postgres_data:/var/lib/postgresql
  harp-server:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

volumes:
  postgres_data:
